global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask'
    static_configs:
      - targets: ['flask-app:5000']

  - job_name: 'mariadb'
    static_configs:
      - targets: ['mysqld_exporter:9104']
